##### Required values
# selenium_namespace
# selenium_chrome_replicas
# application_name
# GITLAB_CI_DEFAULT_SELENIUM_CHROME_IMAGE

##### Install chrome - template
.install_chrome_template:
  script:
    # Delete and re-create the config.toml configmaps that will be mounted into node chrome
    - envsubst < chrome/custom-config.toml > updated-config.toml
    - oc --namespace "${selenium_namespace}" create configmap "selenium-node-chrome-${application_name}" --from-file config.toml=updated-config.toml --dry-run=client -o yaml | oc --namespace "${selenium_namespace}" apply -f -

    # Deploy chrome nodes
    - envsubst < chrome/selenium-node-chrome.yml | oc --namespace "${selenium_namespace}" create -f -
    - oc process "selenium-node-chrome-${application_name}" | oc --namespace "${selenium_namespace}" create -f -

    # Wait for the deployment to complete 
    - oc --namespace "${openshift_namespace}" rollout status "dc/selenium-node-chrome-${application_name}"
